### ISSUE TITLE
workflow currently is CONUS-centric

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-EMC/regional_workflow#1]
Add some generality for handling multiple domains (e.g., CONUS, Hawaii, Alaska, ...)  

[ I have a non-GitHub branch that adds this functionality - just kicking the tires on GitHub before eventually committing my branch here. ]

**Comment by MatthewPyle-NOAA** [comment]
Pull request at:

https://github.com/NOAA-EMC/regional_workflow/pull/2#issue-292587370

**Comment by MatthewPyle-NOAA** [comment]
Second try with a pull request.

https://github.com/NOAA-EMC/regional_workflow/pull/3#issue-293454900

**Comment by JacobCarley-NOAA** [comment]
Closing issue following recent merge to master at [349e2eb](https://github.com/NOAA-EMC/regional_workflow/commit/349e2eb24019990c790b9d51f2fa814edef98ad2)
