### ISSUE TITLE
Generalize parallel run commands inside scripts (e.g. aprun/mpirun/mpiexec)

### ISSUE THREAD

**Issue by JacobCarley-NOAA** [NOAA-EMC/regional_workflow#13]
HAFS workflow has a script which effectively generalizes the parallel run commands, which enhances portability and eases scripting.

**Comment by MatthewPyle-NOAA** [comment]
Bin Liu pointed me at the HAFS job segment which defines a few variables in ways specific to each machine, allowing lower level scripts to use variables to run the parallel executable.  Will hope to look into it more tomorrow.

**Comment by MatthewPyle-NOAA** [comment]
This has been resolved at least for non-DA jobs in the merge_comm_to_EMC branch that likely will be merged into the main develop branch relatively soon.  I think the issue can be closed.
