### ISSUE TITLE
Run SAR workflow components outside of ROCOTO

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [NOAA-EMC/regional_workflow#133]
Add capability to run SAR workflow components outside of ROCOTO (as stand-alone shell scripts).

**Comment by JeffBeck-NOAA** [comment]
Comment

**Comment by llpcarson** [comment]
This needs to be discussed in the context of a community user release.

**Comment by jwolff-ncar** [comment]
Yes! The question comes down to should we really be requiring Rocoto for a community user to run the application? If we do, who supports Rocoto questions? Installing that may be nontrivial for a user on an unsupported platform.

**Comment by JeffBeck-NOAA** [comment]
I agree.  The ability to run in a stand-alone fashion without Rocoto was one of the requirements for the 1st release, so it should be getting more attention soon.  Implementing this capability shouldn't be that hard and could probably be knocked out fairly quickly.

**Comment by jwolff-ncar** [comment]
@llpcarson Any updates to share here? Would you like to use this open issue for your work and point to your PR once it is ready?

**Comment by llpcarson** [comment]
I will use this issue for updates.  I have a set of wrapper scripts that works on cheyenne and hera, without using rocoto.  I need to run through them once more, as there are some odd module-load-path issues that I'm not sure I've solved yet.   I have NOT yet addressed the question of the workflow-generator for a generic-linux platform, will work on that next week.

**Comment by llpcarson** [comment]
PR open #258 , needs to be re-tested on hera following a merge-from-develop;
This method works on any platform that is already supported by the generate_workflow step...  

Next step will be to add a "generic" platform option to the generate_workflow step.

**Comment by llpcarson** [comment]
Completed.  #258
