### ISSUE TITLE
Port to Jet

### ISSUE THREAD

**Issue by jwolff-ncar** [NOAA-EMC/regional_workflow#134]

**Comment by JeffBeck-NOAA** [comment]
Working on this now...

**Comment by climbfuji** [comment]
Hey Jeff, for your info, support for jet within the ufs-weather-model itself (i.e. regular regression testing) will be added back in the current PR (https://github.com/ufs-community/ufs-weather-model/pull/18). The code should compile and run even without the PR.

**Comment by JeffBeck-NOAA** [comment]
Thanks, Dom!  I confirmed that it does compile even without the PR, but
it's good to know there will be regular regression testing there too.

- Jeff

**Comment by jwolff-ncar** [comment]
Should this issue now be closed?

**Comment by JeffBeck-NOAA** [comment]
Yes, I was going to mark that we should resolve it in our task notes, but
please feel free to close it!
