### ISSUE TITLE
Bug fix in workflow launch script (launch_FV3LAM_wflow.sh) for multiple cycles

### ISSUE THREAD

**Issue by gsketefian** [NOAA-EMC/regional_workflow#148]
Fix the way the launch script (ush/launch_FV3LAM_wflow.sh) deals with multiple cycles so that it doesn't set the workflow status to "SUCCESS" after only one cycle has completed successfully.

**Comment by jwolff-ncar** [comment]
What is the status of this, @gsketefian?

**Comment by mkavulich** [comment]
I ran a few tests and it appears that this bug has been resolved, though I'm not sure which commit would have fixed it. @gsketefian can you confirm it is fixed, or did I just get lucky in my tests?

**Comment by gsketefian** [comment]
@mkavulich I have not actively tried to fix it, so you probably got lucky!  It shows up most often when running ensemble tests, especially one with a lot of members (e.g. the WE2E test community_ensemble_008mems).

**Comment by chan-hoo** [comment]
This was fixed by PR https://github.com/NOAA-EMC/regional_workflow/pull/513
