### ISSUE TITLE
Fix workflow launch script for when grid, orog, and/or sfc_climo tasks are turned off.

### ISSUE THREAD

**Issue by gsketefian** [NOAA-EMC/regional_workflow#149]
If the make_grid, make_orog, or make_sfc_climo tasks are turned off, the workflow launch script (ush/launch_FV3SAR_wflow.sh) should still be able determine whether or not the workflow completed successfully (and not just indefinitely leave its status as "IN PROGRESS").

**Comment by jwolff-ncar** [comment]
This is no longer relevant with Jinja templating.
