### ISSUE TITLE
Wiki page documentation

### ISSUE THREAD

**Issue by JacobCarley-NOAA** [NOAA-EMC/regional_workflow#16]
Begin process of introducing workflow documentation to Wiki page.  May also wish to consider adding some guthub notes as well for obtaining/forking/pull requests/code management.

**Comment by ywangwof** [comment]
Outlines are there. Need more reviewers for improvement and fill in the subtopics.

**Comment by mkavulich** [comment]
The wiki is now well-populated. Further content updates can be tracked elsewhere.
