### ISSUE TITLE
Incorporate METplus into community workflow

### ISSUE THREAD

**Issue by jwolff-ncar** [NOAA-EMC/regional_workflow#162]

**Comment by jwolff-ncar** [comment]
Have incorporated grid-stat and point-stat into the workflow so far. Can be found under feature branch of jwolff's fork.

**Comment by JacobCarley-NOAA** [comment]
Tagging @PerryShafran-NOAA as he is involved in this on the EMC side of things.

**Comment by jwolff-ncar** [comment]
@PerryShafran-NOAA Let me know if you have any questions. See: https://github.com/jwolff-ncar/regional_workflow/tree/feature/add_metplus
All of my testing has been done on hera so far. We plan to expand the grid-stat task to run for multiple accumulations with pcp-combine; right now it is only 1h accum.

**Comment by PerryShafran-NOAA** [comment]
@jwolff-ncar Right now I am working on a workflow version of METplus here at EMC, similar to what Mallory had done for the global version of METplus.  Is there something specific that I can focus on in my development?  Did you work with Mallory on this for the global workflow as well?  I don't want to duplicate our efforts.

**Comment by jwolff-ncar** [comment]
Associated with PR #219
