### ISSUE TITLE
Post will segfault for small domains due to over-decomposition

### ISSUE THREAD

**Issue by mkavulich** [NOAA-EMC/regional_workflow#175]
In the community_develop workflow, post tasks will segfault (somewhat inconsistently) for domains below a certain size (approx 500x400 on Hera) due to over-decomposition; this is because post is always assigned the same number of nodes/cores (2:ppn=24) regardless of size.

**Comment by jwolff-ncar** [comment]
@mkavulich Where do things stand with this?

**Comment by mkavulich** [comment]
Fixed by #212 which allows user to specify number of cores for each individual task (for post the relevant variables are PPN_RUN_POST and NNODES_RUN_POST respectively
