### ISSUE TITLE
Streamline the way that MPI decomposition works

### ISSUE THREAD

**Issue by jwolff-ncar** [NOAA-EMC/regional_workflow#177]
The workflow script currently demands that users not only manually specify the MPI domain decomposition, they must also set a variable “blocksize” that is based on the cache size of the machine’s CPU. This is a complete non-starter for supportable community code; people shouldn’t have to randomly guess what the proper MPI settings are for their particular machine.

- Set with grid parameters for pre-defined grids otherwise set in model config file - ask Gerard if need guidance

- Set optimal values on pre-configured platforms

- Set a hard-coded value for other platforms (could just set to 1)

**Comment by JeffBeck-NOAA** [comment]
@jwolff-ncar My understanding is that this work is complete, based on @linlin-pan's PR that was merged a while ago.

**Comment by jwolff-ncar** [comment]
@linlin-pan @panll  Can you point this issue to the closed PR so we can have that information here and close this issue?
Thanks!

**Comment by jwolff-ncar** [comment]
https://github.com/NOAA-EMC/regional_workflow/pull/186
