### ISSUE TITLE
On Cheyenne: some executables randomly segfault

### ISSUE THREAD

**Issue by mkavulich** [NOAA-EMC/regional_workflow#190]
Seemingly randomly, some tasks (including forecast step) can segfault towards the end of execution. Re-running the task seems to work every time. 

I don't believe it is due to the usual suspects (insufficient memory, bad file reads) because

1. The failures seem to hit randomly, and always resolve upon re-run
2. The failures seem to occur during the *deallocation* phase
  - This point essentially rules out insufficient memory, and suggests there may be a problem in the program's deallocation logic.

**Comment by mkavulich** [comment]
Current theory is that this is due to MPI/compiler module mismatches between compiling and running. May take some time to untangle.

**Comment by mkavulich** [comment]
All segfaults have been solved on Cheyenne (PR #204) except for some experiments where the forecast model segfaults. I believe this is due to memory issues, and I am going through the list of pre-defined domains to see which run and which fail.

- [ ] GSD_HAFSV0.A3km
- [x] GSD_HRRR25km
- [ ] GSD_HAFSV0.A3km
- [ ] GSD_HAFSV0.A3km
- [ ] GSD_HAFSV0.A3km
- [ ] GSD_HAFSV0.A3km
- [ ] GSD_HAFSV0.A3km
- [ ] GSD_HAFSV0.A3km
- [ ] GSD_HAFSV0.A3km
- [ ] GSD_HAFSV0.A3km
- [ ] GSD_HAFSV0.A3km
- [ ] GSD_HAFSV0.A3km
- [ ] GSD_HAFSV0.A3km
- [ ] GSD_HAFSV0.A3km
- [ ] GSD_HAFSV0.A3km

**Comment by jwolff-ncar** [comment]
@mkavulich Is this still an issue that needs to be resolved prior to the SRW App v1? The issue is old so I am not sure if it is even still relevant.
