### ISSUE TITLE
GSD_RAP13km pre-defined domain does not run for JPgrid

### ISSUE THREAD

**Issue by mkavulich** [NOAA-EMC/regional_workflow#191]
I have not tested GFDL grid, but for JPgrid and the GSD_RAP13km domain, the run_fcst task segfaults after writing the initial time output file. I do not believe it is a memory issue, as I doubled the number of nodes I was running with and the segmentation fault still occurred at the same point.

This segfault occurs on both Hera and Intel.

**Comment by jwolff-ncar** [comment]
@mkavulich Can this be closed?

**Comment by jwolff-ncar** [comment]
Update test to use the RRFS_NA_3km rather than GSD_RAP13km

**Comment by mkavulich** [comment]
The current end-to-end test (grid_RRFS_NA_13km) runs successfully on Hera.
