### ISSUE TITLE
Fix workflow end-to-end (WE2E) test configuration #13 that tries to run the FV3_GSD_SAR_v1 suite

### ISSUE THREAD

**Issue by gsketefian** [NOAA-EMC/regional_workflow#193]
The name of the suite apparently changed from FV3_GSD_SAR_v1 to (maybe) FV3_GSD_noah.  Change suite name, template file names, etc to the correct names and ensure that this test runs successfully.

I will assign it to Linlin since he is the one who initially created this test.

**Comment by jwolff-ncar** [comment]
@gsketefian I think this SDF has probably changed names at least one other time since this issue was added. Is it still necessary or can it be closed?

**Comment by gsketefian** [comment]
The FV3_GSD_SAR_v1 suite has been removed from the workflow by PR #[287](https://github.com/NOAA-EMC/regional_workflow/pull/287), so this issue is no longer relevant.
