### ISSUE TITLE
Remove USE_CCPP option

### ISSUE THREAD

**Issue by llpcarson** [NOAA-EMC/regional_workflow#196]
Remove the no-CCPP option (USE_CCPP=T/F) from the workflow scripts.

**Comment by jwolff-ncar** [comment]
@gsketefian @llpcarson Hopefully this is still on track? Would be great to have it for the code slush - which will hopefully be "any day now".

**Comment by mkavulich** [comment]
Did not know that referencing this issue would close it...the USE_CCPP code is still in there in various places and should be cleaned up/removed

**Comment by gsketefian** [comment]
@mkavulich I can work on this.  I will start with the develop branch and make a PR.  Question:  Once I do that, I guess I will have to cherry-pick the squash-and-merge commit for that PR onto the HEAD of the release branch, right?

**Comment by gsketefian** [comment]
This was resolved by PR #[308](https://github.com/NOAA-EMC/regional_workflow/pull/308).
