### ISSUE TITLE
ufs-weather-model static build

### ISSUE THREAD

**Issue by llpcarson** [NOAA-EMC/regional_workflow#199]
The ufs-weather-model needs to be compiled in static mode, as the dynamic build option will be removed soon (spring 2020).  
https://github.com/ufs-community/ufs-srweather-app/issues/2

The changes needed i for the runtime scripts are mostly cleanup, as the SDFs are specified at build-time so no LD_LIBRARY_PATH update is needed.

**Comment by jwolff-ncar** [comment]
@llpcarson Is this complete?

**Comment by llpcarson** [comment]
Done, and superseded by cmake/builds
