### ISSUE TITLE
Generation of UPP GRIB2 XML flat file

### ISSUE THREAD

**Issue by hrwinterbottom** [NOAA-EMC/regional_workflow#20]
The HAFS-DA workflow, for post-processing purposes, generates the XML _flat file_ from the XML file such that it enables the community user to modify which variables they wish to dump via UPP to GRIB2 rather than having to edit the flat_file directly.

**Comment by jwolff-ncar** [comment]
I propose this should be closed unless we hear back from @hrwinterbottom. If the branch is stale, it should also be deleted.

**Comment by mkavulich** [comment]
Branch has been deleted per #494
