### ISSUE TITLE
Supported SDFs for community_develop

### ISSUE THREAD

**Issue by JulieSchramm** [NOAA-EMC/regional_workflow#209]
The following suite definition files (SDFs) are valid for running the workflow on the community_develop branch:

valid_vals_CCPP_PHYS_SUITE=( \
"FV3_GFS_2017_gfdlmp" \
"FV3_GSD_v0" \
"FV3_GSD_SAR" \
"FV3_CPT_v0" \
"FV3_GFS_v15p2" \
"FV3_GFS_v16beta" \
"FV3_GSD_SAR_v1" )

The SDF(s) must be specified at build time for the static build.  If no SDFs are specified, all suites in the suite directory will be compiled into the model at build-time, resulting in a longer build, but with the ability to use any suite.  As of now, suite_FV3_GSD_SAR_v1.xml does not exist in ufs-weather-model/FV3/ccpp/suites.

What SDFs should we be using for the ufs-srweather-app static build?

**Comment by jwolff-ncar** [comment]
@gsketefian @JulieSchramm Was it decided we would build to run any of the SDFs available? Is there any additional action that needs to happen for the SRW App v1 release on this issue?
