### ISSUE TITLE
chgres reads the global grib2 file

### ISSUE THREAD

**Issue by panll** [NOAA-EMC/regional_workflow#235]
chgres crushed when read global grib2 file

**Comment by jwolff-ncar** [comment]
@panll @JeffBeck-NOAA I am not sure what this issue refers to. Can you please update as needed or close if addressed?

**Comment by JeffBeck-NOAA** [comment]
@jwolff-ncar This was related to grib2 support for all external model data within chgres_cube, which now exists in the PR I issued a few weeks ago pointing to Larissa's mods in UFS_UTILS.  Closing this issue.
