### ISSUE TITLE
Real-time RRFS-Alaska domain used at GSL is out of sync with repo

### ISSUE THREAD

**Issue by ghost** [NOAA-EMC/regional_workflow#259]
Current values in set_predef_grid_params.sh are inconsistent with real-time configuration, and the lab name "GSD" needs to be removed from the domain name (this also affects valid_param_vals.sh)

**Comment by jwolff-ncar** [comment]
We should update the status, but this is not critical for the UFS SRW App v1 release.

**Comment by jwolff-ncar** [comment]
@gsketefian @JeffBeck-NOAA Can this be closed?
