### ISSUE TITLE
Source postxconfig-NT-fv3sar.txt from EMC_post

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [NOAA-EMC/regional_workflow#262]
Modify regional_workflow to source the postxconfig-NT-fv3sar.txt fixed file from the EMC_post repository instead of using a fixed file within the fix/fix_upp directory.

**Comment by jwolff-ncar** [comment]
@JeffBeck-NOAA Can this issue be closed? I think it has been merged, but I could be missing some component that is still needed.

**Comment by JeffBeck-NOAA** [comment]
@jwolff-ncar Yes, this problem is now resolved.  Closing the issue.
