### ISSUE TITLE
Bug fix for background map plotting in python script

### ISSUE THREAD

**Issue by dmwright526** [NOAA-EMC/regional_workflow#264]
Python plotting script does not allow for contours and background map to be display accurately at the same time. Updating script to allow for both to be displayed.

**Comment by jwolff-ncar** [comment]
Has this issue been sufficiently addressed at this point? Can this be closed?

**Comment by JeffBeck-NOAA** [comment]
This specific issue has been resolved, but there are follow-up problems related to contours and NaN values within the write component output.  @dmwright526 is looking into that currently.  I plan to coordinate with @gsketefian to fix the 25-km CONUS write component output domain, which is to narrow and contains NaNs.
