### ISSUE TITLE
Add the capability for running SDF FV3_RRFS_v1beta

### ISSUE THREAD

**Issue by siwei-noaa** [NOAA-EMC/regional_workflow#269]
The **FV3_RRFS_v1beta** SDF has been released and merged into the ups-weather-model. However, the regional workflow does not have capability/configurations to run FV3_RRFS_v1beta so far. Such capability will be added and tested in the regional workflow.

**Comment by jwolff-ncar** [comment]
Status update for this issue would be helpful - thanks!

**Comment by JeffBeck-NOAA** [comment]
This is complete aside from Mike Toy's GWD script/code.
