### ISSUE TITLE
Update GESROOT in jobs/JFV3CAM_SAR_ENVIR

### ISSUE THREAD

**Issue by jwolff-ncar** [NOAA-EMC/regional_workflow#27]
export GESROOT=${mainroot}/${comdir}/${USER}/com
should be
export GESROOT=${mainroot}/${comdir}/${USER}/nwges

**Comment by JacobCarley-NOAA** [comment]
I think we may want to add a ${gesdir} in place of ${comdir}.

**Comment by BenjaminBlake-NOAA** [comment]
GESROOT has been updated and ${gesdir} was added in place of ${comdir}.
