### ISSUE TITLE
Possible bug in make_solo_mosaic

### ISSUE THREAD

**Issue by gsketefian** [NOAA-EMC/regional_workflow#272]
There may be a bug in the mosaic file creation code (make_solo_mosaic) where the full path to the grid and/or mosaic file(s) must be less than a certain number of characters.  This is suspected because the code crashes with a longer path but works if that path is shortened.  Verify that such a bug exists and if so, fix (fixing requires creating a PR to the UFS_UTILS repo).

**Comment by jwolff-ncar** [comment]
Status update? Is a fix required prior to UFS SRW v1 release?

**Comment by gsketefian** [comment]
This issue was fixed by PR #[156](https://github.com/NOAA-EMC/UFS_UTILS/pull/156) into NOAA-EMC/UFS_UTILS.
