### ISSUE TITLE
Remove model_config.${CCPP_PHYS_SUITE} files from ush/templates

### ISSUE THREAD

**Issue by gsketefian** [NOAA-EMC/regional_workflow#281]
The physics-suite-specific files model_config.${CCPP_PHYS_SUTE} in ush/templates are not needed because the workflow generates a model_config file for a given experiment from the model_config template file in ush/templates (which should NOT be deleted!).

Currently, the model_config template file is not a jinja template.  Modify this file (along with ush/create_model_config_file.sh) to use jinja.

**Comment by christinaholtNOAA** [comment]
Should this also move to a Jinja template at the same time?

**Comment by gsketefian** [comment]
@christinaholtNOAA Let me know if the new issue title/description needs any more mods.  Thx.

**Comment by jwolff-ncar** [comment]
Status update? Is this required prior to UFS SRW v1 release?

**Comment by gsketefian** [comment]
This was resolved by PR #321.
