### ISSUE TITLE
Check setting of stacksize on hera and jet (and other NOAA HPCs?)

### ISSUE THREAD

**Issue by gsketefian** [NOAA-EMC/regional_workflow#298]
Dom says setting stacksize to unlimited is not allowed on NOAA HPC machines.  Check to see if those commands in the script fail.  He uses the following stacksizes on hera and jet (in kb):

hera: 12000000
jet: 16000000

**Comment by jwolff-ncar** [comment]
@gsketefian Is this still an issue or can this be closed?

**Comment by mkavulich** [comment]
The command `ulimit -S unlimited` can not be used on login nodes (for Hera and Jet) but it does work on compute nodes, where it is needed.
