### ISSUE TITLE
Check for pre-existing fix files within make_grid_orog job

### ISSUE THREAD

**Issue by BenjaminBlake-NOAA** [NOAA-EMC/regional_workflow#37]
For the make_grid_orog job, a check will need to be added to see if the grid/orog fix files one needs have already been generated.  If so, the job will exit, and if not, the job will run.  The make_sfc_climo job has a task dependency on the make_grid_orog job completing.

**Comment by mkavulich** [comment]
This capability has since been added. Closing issue.
