### ISSUE TITLE
Enhancements to plot_allvars(_diff).py

### ISSUE THREAD

**Issue by jwolff-ncar** [NOAA-EMC/regional_workflow#376]
@BenjaminBlake-NOAA @dmwright526 
Would you consider writing the output files from running plot_allvars.py (and the diff plot) to the expt_dir rather than the Python dir under the regional_workflow/ush/Python? I think that would make it cleaner to know what plots are from what experiment.

Also, how much work would it be to add in logic to run for a set of forecast hours that could be defined as start_fh, end_fh, increment_fh or something like that?

**Comment by BenjaminBlake-NOAA** [comment]
@jwolff-ncar  Yes, I think both of those suggestions are good, and I can work on that soon.  @dmwright526  Once I finish adding these changes I can let you know if you want to test them out.

**Comment by dmwright526** [comment]
Thanks for working on this @BenjaminBlake-NOAA. I will test it out once you make the changes.

**Comment by BenjaminBlake-NOAA** [comment]
@dmwright526 I made the changes to plot_allvars.py.  They are in the feature/python branch of my fork.  I will add you as a collaborator.  If they look good to you, I can make similar changes to the difference plotting script.  Any suggestions/modifications are welcome if you have ideas for how to improve it!

**Comment by jwolff-ncar** [comment]
That was fast, thanks!

One thing I came across yesterday when I was running these scripts was that when I initialized for a non-00 UTC time (for example at 18 UTC), the script failed because it could not find a file called (for example):
rrfs.t18z.bgdawpf006.tm00.grib2
rather it was called:
rrfs.t18z.bgdawpf006.tm18.grib2
I made a simple change in the scripts to change the lines (shows up once in the all and twice in the diff):
data1 = pygrib.open(EXPT_DIR+'/'+ymdh+'/postprd/rrfs.t'+cyc+'z.bgdawpf'+fhour+'.tm00.grib2')
to:
data1 = pygrib.open(EXPT_DIR+'/'+ymdh+'/postprd/rrfs.t'+cyc+'z.bgdawpf'+fhour+'.tm'+cyc+'.grib2')
I am not sure if this is a universal change that should be applied, but from the behavior I am seeing, I am guessing it is. Can you confirm @BenjaminBlake-NOAA?

**Comment by BenjaminBlake-NOAA** [comment]
Sure!

Yes @jwolff-ncar, that change makes sense.  It should always be tm00, regardless of what cycle time you are making plots for.  Thanks for doing that.

**Comment by dmwright526** [comment]
We had a long conversation about the tm mark back in late July (https://github.com/NOAA-EMC/regional_workflow/pull/250)...

Do we need to change something in the post processing routine to get the naming of the files to be tm00?

**Comment by jwolff-ncar** [comment]
Thanks for the comment @dmwright526. I would say that what was decided there did not translate to what is actually happening in the code so it likely needs an update somewhere... Adding @JeffBeck-NOAA as he was also on that previous thread.

**Comment by JeffBeck-NOAA** [comment]
@jwolff-ncar, it looks like we do need to change the post-processing script to always create tm00 files (as @dmwright526 mentioned), not use the cycle string.  As @BenjaminBlake-NOAA said, it should always be tm00, as the Python script expects.  I can make an issue for this problem.

**Comment by dmwright526** [comment]
@BenjaminBlake-NOAA I wanted to make sure you saw the slight correction I made to the new plot script. I was running into an error on Jet where the variables num and fhours were switching to floats, so I forced them to stay as ints. This change will require the use of NumPy 1.9.0, but I don't think that should be an issue... Could you test it out on your end to make sure it works with your setup?

**Comment by BenjaminBlake-NOAA** [comment]
@dmwright526  Sure I'll test this out today and let you know, thanks

**Comment by BenjaminBlake-NOAA** [comment]
@dmwright526  The changes you added worked for me!  I noticed you commented out reading in the qpf variable so I uncommented that, but otherwise I didn't make any changes.  I can edit the difference plotting script today and let you know when it is ready to test.  Then assuming everything looks good, one of us can create a PR to merge this back to develop.

**Comment by dmwright526** [comment]
@BenjaminBlake-NOAA Sorry! I got in such a rush I forgot to comment back in the qpf variable! Thanks for catching that.

**Comment by BenjaminBlake-NOAA** [comment]
@dmwright526 No problem!

For the difference plotting script, do we want to assume that the plots are for the same valid time or should we not make that assumption?  Currently we define the cycle date/time twice for each experiment but perhaps that can be removed.  I guess the starting/ending forecast hours and forecast increment will need to be the same for both files though.

**Comment by jwolff-ncar** [comment]
I guess it is possible someone would want to diff two different forecast times to see how something changed over time. You would need to make sure that the same number of start/end/increment times are set for both, but those could be for different valid times. Maybe leave it defined twice for now? But I could honestly go either way. That was not necessarily the intent for these scripts so you could also let users create their own (or modify these) scripts if they want to do something beyond what is provided?

**Comment by jwolff-ncar** [comment]
@BenjaminBlake-NOAA BTW, I also tested the updates to the initial script on hera and with the addition of @dmwright526 modifications it worked great. Thanks!

**Comment by BenjaminBlake-NOAA** [comment]
@jwolff-ncar  Ok great, thanks for testing it!  Hmm I think it would make things simpler to assume that the plots are for the same valid time, so if you could go either way then I'll go ahead and do that.  If the user would like to diff two different forecast times, they should be able to edit/modify the script as you noted.

**Comment by BenjaminBlake-NOAA** [comment]
@dmwright526 @jwolff-ncar  I made the changes for the plot_allvars_diff.py script and pushed the new version to my feature/python branch.  Feel free to test it out when you get a chance!

**Comment by dmwright526** [comment]
@BenjaminBlake-NOAA, sorry for letting this sit. I just tested the diff plotting on Jet and it worked great for me!

**Comment by BenjaminBlake-NOAA** [comment]
No problem, thanks for testing!  @jwolff-ncar  Should I go ahead and submit a PR for these changes?

**Comment by jwolff-ncar** [comment]
@BenjaminBlake-NOAA Please feel free! I will do another quick test today on the diff script. Thanks for your work on these!

**Comment by BenjaminBlake-NOAA** [comment]
Sure!  I just created the PR and I can add you as a reviewer if you'd like.

**Comment by jwolff-ncar** [comment]
We just need to keep in mind that @JeffBeck-NOAA will also have a corresponding change to modify the names of the UPP output to be tm00 rather than tm+cyc+
