### ISSUE TITLE
Set tmmark to always be tm00 in exregional_run_post.sh script.

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [NOAA-EMC/regional_workflow#379]
Currently the tmmark for post files is set as follows in exregional_run_post.sh:

tmmark="tm$hh"

Since we have no DA implementation yet, this should be:

tmmark=tm00

@jwolff-ncar @BenjaminBlake-NOAA @dmwright526

**Comment by jwolff-ncar** [comment]
I am pretty sure this was included. Please reopen if necessary.
