### ISSUE TITLE
develop: Add user-defined interval date option for experiment generation

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [NOAA-EMC/regional_workflow#392]
In ush/set_cycle_dates.sh, the experiment directories are defined as:

  date_crnt="${date_start}"
  while [ "${date_crnt}" -le "${date_end}" ]; do
    all_cdates+=( $( printf "%s " ${cycle_hrs[@]/#/${date_crnt}} ) )
    date_crnt=$( date -d "${date_crnt} + **1 days**" +%Y%m%d )
  done

There is interest in having a user-defined interval date value which would replace the "1 days" in the date command with whatever the user would like to use.  For example, every three days could be implemented with ${DATE_INTERVAL}=3 in config.sh, and:

  date_crnt="${date_start}"
  while [ "${date_crnt}" -le "${date_end}" ]; do
    all_cdates+=( $( printf "%s " ${cycle_hrs[@]/#/${date_crnt}} ) )
    date_crnt=$( date -d "${date_crnt} + **${DATE_INTERVAL} days**" +%Y%m%d )
  done

The default ${DATE_INTERVAL} value would be set to one in config_defaults and used if undefined in config.sh.

**Comment by jwolff-ncar** [comment]
In addition, generate_FV3LAM_wflow.sh is also set to be a daily increment
‘cycl_freq’: !!str 24:00:00

We would like the ability to set an increment (in hours) to have more flexibility in this setting. And this should become a user-defined setting that can be passed in through the config.sh.
