### ISSUE TITLE
Import the regional_grid into the build system

### ISSUE THREAD

**Issue by BinLiu-NOAA** [NOAA-EMC/regional_workflow#42]
Import the regional_grid into the build system and the corresponding source code will be included in a branch of UFS_UTILS. Make sure it supports theia, wcoss_dell_p3 and wcoss_cray.

**Comment by JacobCarley-NOAA** [comment]
Was merged into develop at [94f30e7](https://github.com/NOAA-EMC/regional_workflow/commit/94f30e7fb5f03ab69a75b933e5ce5f472ff949ae)
