### ISSUE TITLE
Path to staged data for WE2E tests on Cheyenne is incorrect

### ISSUE THREAD

**Issue by jwolff-ncar** [NOAA-EMC/regional_workflow#464]
Path to staged data on Cheyenne is incorrect

Currently:
elif [ "$MACHINE" = "CHEYENNE" ]; then
      extrn_mdl_source_basedir="/glade/p/ral/jntp/UFS_CAM/staged_extrn_mdl_files"

Should be updated to be 
    elif [ "$MACHINE" = "CHEYENNE" ]; then
      extrn_mdl_source_basedir="/glade/p/ral/jntp/UFS_SRW_app/staged_extrn_mdl_files"

**Comment by mkavulich** [comment]
Good catch @jwolff-ncar, the tests still work due to a symlink left behind (/glade/p/ral/jntp/UFS_CAM/ --> /glade/p/ral/jntp/UFS_SRW_app) but this should definitely be updated. I can roll that into a future change.

**Comment by jwolff-ncar** [comment]
PR merged to fix. Done.
