### ISSUE TITLE
In the documentation, include a calling tree for the regional_workflow scripts

### ISSUE THREAD

**Issue by gsketefian** [NOAA-EMC/regional_workflow#469]

**Comment by chunhuazhou** [comment]
A calling tree of the scripts would be really helpful!

**Comment by chan-hoo** [comment]
@chunhuazhou, do you mean a flowchart as shown in https://drive.google.com/file/d/12r9mSHSYgI5O3Whgeit9pIGmfIcoRm7T/view?usp=sharing (Figure 2.3, pp. 31)? If so, what scripts do you want to see? If not, do you have any examples?
