### ISSUE TITLE
Update CCPA pull script to handle the bug fix data appropriately

### ISSUE THREAD

**Issue by jwolff-ncar** [NOAA-EMC/regional_workflow#487]
A CCPA tar file contains a 00, 06, 12, and 18 directory. In the 00 directory -- for example, in 20190616/00, there are files for 19-00. The hourly GRIB2 files say they are valid at 2019061619, 2019061620, 2019061621, 2019061622, 2019061623, and 2019061700; however, they are actually valid at 2019061519, 2019061520, 2019061521, 2019061522, 2019061523, and 2019061600, respectively.

This is bad! BUT! It only occurs for 1-h files. All 3-h and 6-h accumulations are okay.

Yan Luo has confirmed our findings. A bug fix has been issued; however, implementation of the fix is postponed to next CCPA upgrade.

Update: This is to inform you that the CCPA bug fix (CCPAv4.1.3) has been implemented to production since yesterday (5/4/2021). The bug remains in the 00Z directory 1-hour data for a period of 7/18/2018-5/4/2021 (running dates). The bug disappears in the new runs after 5/4/2021.

**Comment by jwolff-ncar** [comment]
@michelleharrold I think you have a fix for this in your fork, correct? Will you just make sure this issue is updated as needed when that goes into a PR?

**Comment by michelleharrold** [comment]
@jwolff-ncar - I haven't tested it fully yet, but yes. I will be sure to make sure we are good to go!

**Comment by jwolff-ncar** [comment]
@michelleharrold I have not thoroughly looked through your PR yet - we need to remember to close this issue once that PR has been merged since it is addressed there.

**Comment by JiliDong-NOAA** [comment]
I see the current script has the following to handle the CCPA data mismatch (the last two elif):

```
# One hour CCPA files have incorrect metadeta in the files under the "00" directory. After data is pulled, reorganize into correct valid yyyymmdd structure.
      if [[ ${vhh_noZero} -ge 1 && ${vhh_noZero} -le 6 ]]; then
        cp $ccpa_raw/${vyyyymmdd}/06/ccpa.t${vhh}z.${accum}h.hrap.conus.gb2 $ccpa_proc/${vyyyymmdd}
      elif [[ ${vhh_noZero} -ge 7 && ${vhh_noZero} -le 12 ]]; then
        cp $ccpa_raw/${vyyyymmdd}/12/ccpa.t${vhh}z.${accum}h.hrap.conus.gb2 $ccpa_proc/${vyyyymmdd}
      elif [[ ${vhh_noZero} -ge 13 && ${vhh_noZero} -le 18 ]]; then
        cp $ccpa_raw/${vyyyymmdd}/18/ccpa.t${vhh}z.${accum}h.hrap.conus.gb2 $ccpa_proc/${vyyyymmdd}
      elif [[ ${vhh_noZero} -ge 19 && ${vhh_noZero} -le 23 ]]; then
        wgrib2 $ccpa_raw/${vyyyymmdd_p1}/00/ccpa.t${vhh}z.${accum}h.hrap.conus.gb2 -set_date -24hr -grib $ccpa_proc/${vyyyymmdd}/ccpa.t${vhh}z.${accum}h.hrap.conus.gb2 -s
      elif [[ ${vhh_noZero} -eq 0 ]]; then
        wgrib2 $ccpa_raw/${vyyyymmdd}/00/ccpa.t${vhh}z.${accum}h.hrap.conus.gb2 -set_date -24hr -grib $ccpa_proc/${vyyyymmdd}/ccpa.t${vhh}z.${accum}h.hrap.conus.gb2 -s
      fi
```

Since the bug is fixed in CCPA after 2021/05/04, could a switch be added based on the CCPA bug fix date (doing the bug fix before 2021/05/04 and not doing it after the date)?

Thanks.
