### ISSUE TITLE
Merging the scripts of the fully cycled fv3sar ensemble based hybrid GSI analysis and EnKf  

### ISSUE THREAD

**Issue by TingLei-daprediction** [NOAA-EMC/regional_workflow#50]
Currently, a fully cycled FV3SAR ensemble based hybrid GSI analysis and EnKF system has been developed and evaluated. This issue is to merge the modified scripts and additional scripts to the current regional-workflow while following the latter's format/standard when possible.

**Comment by TingLei-NOAA** [comment]
The merging with the newer develop branch of  EMC regional workflow with major upgrades has been finished and tested.  The developed branch is regional-workflow-fv3sar_ens. 
How to push back this branch to the current develop branch of EMC regional workflow is to be decided.

**Comment by jwolff-ncar** [comment]
What is the status of this issue?

**Comment by TingLei-daprediction** [comment]
@jwolff-ncar Thanks for asking.  A "then EMC"  workflow based hybrid var-enkf da system for fv3-lam has been developed maintained.  A recent version is the branch regional-workflow-GFSv16-fv3sar_ensda at https://github.com/TingLei-daprediction/regional_workflow.git , which has been running on hera and need to be tested  on WCOSS since there are a few new functions added recently.  The problem is the "then EMC workflow" is different from the current EMC-workflow (the unified community weather app workflow), in the release of the latter the DA component is absent yet.  Some efforts on DA component for the unified community weather app are ongoing, though the functions for a self cycled fv3-lam (through enkf) with the latter seems to be not available to me in a short time frame.  @JacobCarley-NOAA ,@christinaholtNOAA and Ming Hu could have their comments.

**Comment by jwolff-ncar** [comment]
I recommend we close this issue and create a new one as continued development happens in the soon-to-be created RRFS development branch as necessary. Are you ok with that?

**Comment by TingLei-NOAA** [comment]
Sure, I am ok with closing this issue.
Thanks.
Ting

______________________________

Ting Lei

IMSG at NOAA/NWS/NCEP/EMC

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3624
