### ISSUE TITLE
Running develop branch on Theia

### ISSUE THREAD

**Issue by mkavulich** [NOAA-EMC/regional_workflow#55]
@BenjaminBlake-NOAA I was looking in to running the workflow as it exists on the develop branch. I was told that you or @MatthewPyle-NOAA may be working on an XML that will run the full workflow on Theia. Is this correct? If not I will build an XML myself for Theia and commit it to the develop branch.

**Comment by MatthewPyle-NOAA** [comment]
I have started some Theia work in my fork as a part of work to generalize the parallel execution commands (mpirun/srun/aprun/....), but the work has been sporadic thus far.  I hope to get back to it next week, but will be leaving for vacation on 8/15, so might not have something ready very quickly.  So if you need it soon, you might be best off doing it yourself.  Not sure if @BenjaminBlake-NOAA has done more with a more general port of develop to Theia.

**Comment by BenjaminBlake-NOAA** [comment]
Hi Mike, unfortunately I have not had time to work on the general port of develop to Theia with the other tasks I've had to complete.  If you'd like to build an xml and add it to develop I'd be happy to test it out on Theia.

**Comment by JacobCarley-NOAA** [comment]
@MatthewPyle-NOAA maybe @mkavulich could start with your fork and work from there?

**Comment by MatthewPyle-NOAA** [comment]
There now are plans for a mini code sprint here on Monday related to Theia - @BinLiu-NOAA has offered to help @BenjaminBlake-NOAA  and me.  So depending on how that goes it might result in something better than my fork.

**Comment by JacobCarley-NOAA** [comment]
Tagging @hongli-wang as he is starting to get spun up on Theia and progress on this is of interest.

**Comment by mkavulich** [comment]
Thanks for the responses @MatthewPyle-NOAA, I'd appreciate it if you could update me after Monday's work, then I can continue based on the best available starting point at that time.

**Comment by BenjaminBlake-NOAA** [comment]
Hi @mkavulich, @MatthewPyle-NOAA @BinLiu-NOAA and myself have been working on an xml template to run the develop branch on Theia.  The make IC/BC and forecast jobs complete successfully and we are testing the post jobs today.  Once the latest changes have been committed to the feature/merge_comm_to_EMC branch we will let you know.

**Comment by hongli-wang** [comment]
Great! Thanks for the update. I will check it out and test it when it is ready.

**Comment by hongli-wang** [comment]
@BenjaminBlake-NOAA Is the workflow on Theia include GSI DA? Thanks.

**Comment by BenjaminBlake-NOAA** [comment]
@hongli-wang Unfortunately not at this time!

**Comment by BenjaminBlake-NOAA** [comment]
Hi all, with the latest changes committed to feature/merge_comm_to_EMC you should be able to run the EMC workflow on Theia.  Bin/Matt/I successfully tested the make_ic, make_bc, forecast, post, post_goes, and cleanup jobs.  Bin has sample data available on Theia for 2019050200 or you could use your own data.  The one file you'll need to edit is rocoto/run_regional_theia.sh.  Let us know if you have any questions.  Thanks!

**Comment by hongli-wang** [comment]
@BenjaminBlake-NOAA Thanks for the update. I will check out and test the EMC workflow on Theia.  Hongli

**Comment by hongli-wang** [comment]
@BenjaminBlake-NOAA @JacobCarley-NOAA Tested the workflow using the sample data for 2019050200, make_ic, make_bc, forecast were successful. However, when changed to my fv3gfs forecasts, it needs to define COMINgfs (path of fv3gfs forecasts) in jobs/JREGIONAL_ENVIR or passed COMINgfs to it to make make_bc work. Thanks for making SAR work on Theia!

**Comment by BenjaminBlake-NOAA** [comment]
@hongli-wang Great!  I'm glad to hear it worked.  Are you referring to COMINgfs or COMgfs?  I know COMgfs is passed in through run_regional_theia.sh, and it looks like COMINgfs and COMgfs are both defined in JREGIONAL_ENVIR already.

Once I am able to commit these changes to the develop branch (first I need to test the changes on WCOSS Dell to make sure nothing was broken) I will close this issue.

**Comment by hongli-wang** [comment]
@BenjaminBlake-NOAA I mean COMINgfs. I manually changed COMINgfs in JREGIONAL_ENVIR to my own fv3gfs forecast directory to make make_bc work.

**Comment by BenjaminBlake-NOAA** [comment]
@hongli-wang Ok I see what you mean, COMINgfs should be defined in run_regional_theia.sh so that the user can change it there.  Thanks for finding that.

**Comment by BinLiu-NOAA** [comment]
@BenjaminBlake-NOAA My suggestion would be replacing COMgfs with COMINgfs everywhere (within the script and workflow definition file), according to the EE2 and implementation standard.

**Comment by BenjaminBlake-NOAA** [comment]
@BinLiu-NOAA That is a good point and you are right, thanks.  I checked the NCO implementation standards document and they recommend using $COMINmodel as opposed to $COMmodel.  This should not be difficult to change.
