### ISSUE TITLE
WE2E tests fail on Orion due to incorrect location of input data

### ISSUE THREAD

**Issue by mkavulich** [NOAA-EMC/regional_workflow#550]
# Description

All WE2E tests on Orion fail due to incorrect locations of input data. Either the locations of input data need to be updated or the scripts need to be changed to look in a different location

## Steps to Reproduce

Run any WE2E test on Orion. I saw this issue specifically for DOT_OR_USCORE, GST_release_public_v1, and grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 in my latest set of tests, but I believe it impacts all tests.

**Comment by chan-hoo** [comment]
The above WE2E tests are complete successfully on Orion as of 11/05/21.
