### ISSUE TITLE
Make the static build of CCPP the default for all machines

### ISSUE THREAD

**Issue by BenjaminBlake-NOAA** [NOAA-EMC/regional_workflow#58]

**Comment by jwolff-ncar** [comment]
CCPP should probably be the only option as we prepare for a release. What does this entail at this point?

**Comment by BenjaminBlake-NOAA** [comment]
I agree.  We will be switching our real-time runs to use CCPP within the next 1-2 weeks.  For the current develop branch this just involves a simple change to the build configuration script to only build the model with CCPP.  Since we are in the process of merging with the community develop branch we can probably close this issue if that makes the most sense.
