### ISSUE TITLE
crontab setting

### ISSUE THREAD

**Issue by panll** [NOAA-EMC/regional_workflow#586]
@RaghuReddy-NOAA sent me an email about setting in the crontab to run the workflow
*/3 * * * * 
Is it possible to reduce the loading frequency to decrease the load to the system? e.g.,
*/5 * * * *

**Comment by chan-hoo** [comment]
You can specify the cron interval minute by setting 
USE_CRON_TO_RELAUNCH="TRUE"
CRON_RELAUNCH_INTVL_MNTS="5" 
in 'config.sh'.
