### ISSUE TITLE
The repository name of 'EMC_post' was changed to 'UPP'.

### ISSUE THREAD

**Issue by chan-hoo** [NOAA-EMC/regional_workflow#589]
# Description

Since the repository name of 'EMC_post' was changed to 'UPP' (https://github.com/NOAA-EMC/UPP), the external name for post-processing and some prefixes in multiple scripts should be changed from 'EMC_post' to 'UPP'.

**Comment by JeffBeck-NOAA** [comment]
Beat me to it, @chan-hoo!  Thank you!
