### ISSUE TITLE
Port to Hera

### ISSUE THREAD

**Issue by BenjaminBlake-NOAA** [NOAA-EMC/regional_workflow#82]
Hera will be the replacement for Theia; Theia is going away at the end of September.  This port should not require a large amount of work, as the system architecture of Hera is apparently quite similar to that of Theia.  In addition, Jim Abeles has already run several tests with the regional FV3 on Hera.

**Comment by jwolff-ncar** [comment]
@BinLiu-NOAA @BenjaminBlake-NOAA Can this be closed? We are running the community workflow on Hera. Are you still testing there?

**Comment by BenjaminBlake-NOAA** [comment]
Hi Jamie, yes this can be closed!
